package rms.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("type", "id", Type.class);
		arp.addMapping("plan", "id", Plan.class);
		arp.addMapping("project", "id", Project.class);
		arp.addMapping("risk", "id", Risk.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("trail", "id", Trail.class);
		arp.addMapping("user", "id", User.class);
	}
}

