package rms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUser(java.lang.Integer user) {
		set("user", user);
	}

	public java.lang.Integer getUser() {
		return get("user");
	}

	public void setProject(java.lang.Integer project) {
		set("project", project);
	}

	public java.lang.Integer getProject() {
		return get("project");
	}

	public void setRole(java.lang.String role) {
		set("role", role);
	}

	public java.lang.String getRole() {
		return get("role");
	}

}
